### ISSUE TITLE
Feature request - make this a packaged Github Action 

### ISSUE THREAD

**Issue by mvs5465** [Skarlso/dependabot-bundler#21]
Awesome repo, we'd like to look into using this. As a feature request - would it be possible to turn this into a packaged Github Action?

Would be nice to be able to do something like this:

```
name: Dependabot Bundler
on:
  pull_request:
jobs:
  dependabot-bundler:
    uses: Skarlso/dependabot-bundler@v0.0.3
```

**Comment by Skarlso** [comment]
Hello! :) Sure. It could be done indeed. :)

**Comment by Skarlso** [comment]
Meanwhile, it's actually quite easy to set it up if you already have a go project. For example look at this:

```yaml
name: Dependabot Bundler

on: workflow_dispatch

jobs:
  bundler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Cache go-build and mod
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Install Dependabot Bundler
        run: |
          go install github.com/Skarlso/dependabot-bundler@v0.0.10
      - name: Run Dependabot Bundler
        run: |
          dependabot-bundler --token ${{ secrets.GITHUB_TOKEN }} --repo eksctl --owner weaveworks --labels skip-release-notes,dependencies
```
